### ISSUE TITLE
Upgrade extract-text-webpack-plugin to 2.1.2 from 2.1.1

### ISSUE THREAD

**Issue by yingw787** [KleoPetroff/react-webpack-boilerplate#124]
## The problem

Just downloaded the boilerplate and it broke on npm start with extract-text-webpack-plugin, relating to absolute vs. relative path issue noted here: https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/536

## Details

Update version number in package.json, reinstall node_modules, and everything works fine. Just a heads up.

**Comment by KleoPetroff** [comment]
Thank you @yingw787! It's strange that the greenkeeper didn't update the dependency, nor the CI failed. I've manually updated the package to version 2.1.2.
