### ISSUE TITLE
commands not working in Windows environment

### ISSUE THREAD

**Issue by KishoreBarik** [KleoPetroff/react-webpack-boilerplate#171]
1. Clean and Production commands failing in windows.
2. I don't see a dist folder here. (May be will be created on production command)
3. Which index.html to be modified app/index.html or build/html? 
As I don't see changes done in app/index.html is not reflected in `npm start` command

**Comment by KleoPetroff** [comment]
1. Please provide more information, `npm-debug` log would be a good start. 
2. The dist folder is created on production build only.
3. `index.html` in the app folder is used for the production build. The one in the build folder is used for development purposes only. If you want to see the changes when using `npm start`, this is the file you need to look for.

**Comment by KishoreBarik** [comment]
Sorry for the late reply and thanks for clarification on index.html. I thought same index.html is used for both dev and production. Hence we might need to make changes in both places. And other issue was resolved by installing webpack as global module. Hence closing the issue.
