### ISSUE TITLE
Problem with loading fonts. File-loader

### ISSUE THREAD

**Issue by khusainovk** [KleoPetroff/react-webpack-boilerplate#193]
## Problem with loading fonts. File-loader
Hey,
I had a problem with font loading. I wrote correct path to the fonts and there was 404 error.
I solved that issue by changing version of `file-loader` to the `0.11.2` version

**Comment by KleoPetroff** [comment]
Hey @khusainovk,

`file-loader`'s version was indeed the cause of the problem and reverting it to `0.11.2` seems to fix the problem. Thank you very much for the help on this!

**Comment by Pizdetss** [comment]
This isn't working for me. 
Got Fonts path as /assets/fonts/something.ttf

Even tried reverting back to file-loader 0.11.2 and still have 404.
