### ISSUE TITLE
Add Server Side Rendering

### ISSUE THREAD

**Issue by danjonesdev** [KleoPetroff/react-webpack-boilerplate#204]
Hi, Would it be possible to have an Express server with SSR in this project?

**Comment by KleoPetroff** [comment]
Hi, @danjonesdev, I don't have any plans for SSR at the moment. You can fork the repo and add it by yourself. I will gladly help you with the implementation.

**Comment by danjonesdev** [comment]
Sweet mate, I'll have a go at implementing this myself and will no doubt pester you in the near future! :)
