### ISSUE TITLE
Refresh on deeper links does not work

### ISSUE THREAD

**Issue by neerajhiretual** [KleoPetroff/react-webpack-boilerplate#297]
## The problem

Whenever i am in deeper links, and try to refresh, i get 404 error like 
`http://localhost:8080/home/styles/style.css`
`http://localhost:8080/home/bundle.js `

## Details

If you have a link in your application such as `http://localhost:8080/home/integration`. And you do a refresh on the page. It somehow starts looking for style.css and bundle.js in `http://localhost:8080/home` instead of `http://localhost:8080/`. I am not exactly sure, where the real issue is. I just dug a little deeper and i think, its a problem with webpack.config.js.
I have below thing in my webpack.config.js:
`devServer: {`
`    hot: true,`
`    historyApiFallback: true,`
`    contentBase: resolve(__dirname, 'build'),`
`    publicPath: '/',`
`  },`

Will you be able to guide something here?

**Comment by neerajhiretual** [comment]
Can you give me some direction.
I can fix the issue and create a PR.

**Comment by KleoPetroff** [comment]
Hey @neerajhiretual, sorry for taking so long, but I have some IRL matters I have to deal with. The moment I have more time, I will investigate this. In the meantime, if you've resolved the issue, a PR will gladly be appreciated.

**Comment by neerajhiretual** [comment]
I don't know if this is the exact solution.
I added `<base href="/">` in build/index.html and index.html, both files.
Seems to fix the issue.

**Comment by KleoPetroff** [comment]
The issue should be resolved now.
