### ISSUE TITLE
Warning and Bug: in react-hot-loader: 4.0.0-beta.1

### ISSUE THREAD

**Issue by EmeraldWeb** [KleoPetroff/react-webpack-boilerplate#312]
## The problem
Warnings in console :
`Error while wrapping name -> TypeError: Object.defineProperty called on non-object`, which is received from react-hot-loader.
![warning](https://user-images.githubusercontent.com/20793330/36718173-a2411166-1bc2-11e8-9e55-22628471e400.png)

Bug/Error while building the project for production: 
```
ERROR in bundle.js from UglifyJs
Unexpected token: name (exportedModule) [bundle.js:1564,4]
```
When babel-loader transpile your .js inside bundle he ignore/misses variable inside react-hot-loader.
`let exportedModule;` not transpiled in `var`. UglifyJs don't work with es6 and fall down whith this error. 

## Details
On npm install command, i get version of "react-hot-loader": "4.0.0-beta.1", in this version i have this warnings and this bug/error. Warnings described in this issue :
https://github.com/gaearon/react-hot-loader/issues/804
And fixed in version 4.0.0-beta.16 . So I tested this version, it works and resolve warnings and bug/error.
I suggest upgrading to this version in package.json.
Thank you for attention.

**Comment by KleoPetroff** [comment]
The currently used version of react-hot-loader is 4.0.0-rc.0 and I don't see any warning or error. I've even tried with version 4.0.0 and the result was the same. Are you sure you are not using an old version?

**Comment by EmeraldWeb** [comment]
I downloaded the ZIP-archive and inside it was `"react-hot-loader": "4.0.0-beta.1",` Now i download ZIP again and its normal `"react-hot-loader": "4.0.0",`
I apologize for the extra issue and you can close it.
