### ISSUE TITLE
Problem with Webpack

### ISSUE THREAD

**Issue by sirLisko** [KleoPetroff/react-webpack-boilerplate#57]
## The problem

Running `npm start` just after installing all the dependencies via `npm install` an error is triggered. 

## Details

```
➜  react-webpack-boilerplate-master npm start

> react-webpack-boilerplate@2.0.0 start /Users/luca/Downloads/react-webpack-boilerplate-master
> webpack-dev-server --devtool source-map --hot --inline --content-base public --history-api-fallback

keywords if/then/else require v5 option
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'outputPath'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
```

I tried to install the exact version of each module (removing `^` from `package.json`) and a different error is triggered.

Maybe using something as `npm shrinkwrap` would solve this kind of problem, at least till `webpack` will be in `beta`.

**Comment by KleoPetroff** [comment]
Hey @sirLisko, thank you for bringing up the issue. I didn't have much time the last months to look after the project, but I have plans for refactoring the whole code base. As soon as I get back from the holidays, I will start working on this.

**Comment by sirLisko** [comment]
No worries and thanks for your quick reply :)
I was looking for some examples about `React` + `Webpack` and your repo seemed the most simple to start from :)

At the end, I decided to keep my `jspm` build for the moment and wait for a stable `webpack`.

**Comment by danjonescidtrix** [comment]
+1

**Comment by KleoPetroff** [comment]
First, sorry for taking so long. I've updated the project, you can see the changelog here - [releases/v3](https://github.com/KleoPetroff/react-webpack-boilerplate/releases/tag/v3.0.0). You should be able to start the dev server without any problems now.

Reopen the issue if anything else gets on your way. :slightly_smiling_face:
