### ISSUE TITLE
First run - unable to locate './vendors'

### ISSUE THREAD

**Issue by Si1kIfY** [KleoPetroff/react-webpack-boilerplate#65]
## The problem

`npm start` fails at step copy-webpack-plugin

```
ERROR in [copy-webpack-plugin] unable to locate './vendors' at '/Users/csilk/dev/react-webpack-boilerplate/app/vendors'
```

## Details

1. Cloned the repo
2. `$ npm install`
3. `$ npm start`

```
npm ERR! react-webpack-boilerplate@2.0.0 production: `npm run clean && webpack --config webpack.production.config.js --progress --profile --colors`
npm ERR! Exit status 2
```

Run on two seperate environments:

### Environment 1 

Mac OS X El capitan - 10.11.6
Node - v6.9.1
NPM - v4.2.0

### Environment 2

Mac OS X El capitan - 10.11.6
Node - v7.4.0
NPM - v4.2.0

**Comment by Si1kIfY** [comment]
Seems to be trying to copy a folder that doesn't exist?

https://github.com/KleoPetroff/react-webpack-boilerplate/blob/master/webpack.production.config.js#L47

And

https://github.com/KleoPetroff/react-webpack-boilerplate/blob/master/webpack.config.js#L68

**Comment by KleoPetroff** [comment]
The fastest way to fix this is to create an empty vendors page in `app` and run `npm start` again.

I'm not sure if copy-webpack-plugin or webpack have a way to skip execution if the folder does not exist. If not, I will just add the vendors' folder in `app`.

**Comment by KleoPetroff** [comment]
Seems that adding the `vendors` folder to `app` was the only possible solution.
