### ISSUE TITLE
Update with Redux

### ISSUE THREAD

**Issue by nagibmahfuj** [KleoPetroff/react-webpack-boilerplate#83]
It is a great starter, just update with Redux. Cheers!

**Comment by KleoPetroff** [comment]
Thank you, @nagibmahfuj. Redux is definitely coming. :wink:

**Comment by arcifius** [comment]
Agreed, its a nice starter... Redux is nice but there are other state managers... Maybe you can keep things as they are, this way we can use any state manager we want instead of removing your redux part to use another one... Just an idea (;

**Comment by danjonesdev** [comment]
I prefer this boilerplate _because_ it is without a state manager, maybe have a separate branch for Redux?
