### ISSUE TITLE
no coverage?

### ISSUE THREAD

**Issue by Bamieh** [KleoPetroff/react-webpack-boilerplate#94]
## The problem

You are running unit tests without coverage.

**Comment by KleoPetroff** [comment]
Fair point, but I want to keep things simple. People using the boilerplate, me including, can integrate a coverage tool by their taste. I'll leave that choice to them. Also, most of the example code would most definitely change or be removed, so adding more tests to keep a high % of coverage, that will later be deleted seems like unnecessary extra work.

**Comment by Bamieh** [comment]
its your call, however i want to point out that there is no need to keep the % high for a boilerplate. Also, having `nyc` for coverage will keep things super simple.

**Comment by KleoPetroff** [comment]
I've thought about it this morning and you have a point - `nyc` is super simple to integrate and would indeed benefit the project. I may end up adding it after all. :wink: 

I'm reopening the issue.

**Comment by Bamieh** [comment]
i can submit a pull request

**Comment by KleoPetroff** [comment]
That would be great!
